-- AlterTable
ALTER TABLE `amazon_inbound_shipments`
ADD COLUMN `shipment_confirmation_id` VARCHAR(128) NULL AFTER `amazon_shipment_id`;

-- AlterEnum
ALTER TABLE `operation_audit_logs`
MODIFY `event_type` ENUM(
  'box_created',
  'box_field_updated',
  'box_renamed',
  'box_disabled',
  'box_deleted',
  'box_stock_increased',
  'box_stock_outbound',
  'sku_created',
  'sku_field_updated',
  'sku_disabled',
  'sku_deleted',
  'shelf_created',
  'shelf_field_updated',
  'shelf_disabled',
  'shelf_deleted',
  'brand_created',
  'brand_updated',
  'brand_deleted',
  'sku_type_created',
  'sku_type_updated',
  'sku_type_deleted',
  'shop_created',
  'shop_updated',
  'shop_deleted',
  'user_created',
  'user_updated',
  'user_disabled',
  'user_deleted',
  'inbound_order_created',
  'inbound_order_confirmed',
  'inbound_order_voided',
  'outbound_order_created',
  'outbound_order_confirmed',
  'outbound_order_voided',
  'stocktake_task_created',
  'stocktake_task_started',
  'stocktake_task_finished',
  'stocktake_task_voided',
  'inventory_adjust_created',
  'inventory_adjust_confirmed',
  'inventory_adjust_voided',
  'amazon_connection_created',
  'amazon_connection_updated',
  'amazon_connection_deleted',
  'amazon_inbound_job_created',
  'amazon_inbound_job_payload_built',
  'amazon_inbound_job_pushed',
  'amazon_inbound_job_push_failed',
  'amazon_inbound_job_sync_failed',
  'amazon_inbound_job_synced',
  'amazon_inbound_job_placement_updated',
  'amazon_inbound_job_transportation_updated',
  'amazon_inbound_job_labels_updated',
  'amazon_inbound_job_shipments_synced',
  'amazon_inbound_job_packing_updated',
  'amazon_inbound_job_packing_information_updated'
) NOT NULL;
