-- CreateTable
CREATE TABLE `order_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `row_hash` CHAR(40) NOT NULL,
  `order_id` VARCHAR(64) NULL,
  `item_detail_status` VARCHAR(64) NULL,
  `sku_code` VARCHAR(128) NULL,
  `set_component_sku_code` VARCHAR(128) NULL,
  `order_quantity` INTEGER NULL,
  `product_name` TEXT NULL,
  `mall_name` VARCHAR(128) NULL,
  `shop_name` VARCHAR(128) NULL,
  `mall_order_no` VARCHAR(128) NULL,
  `order_status_text` VARCHAR(64) NULL,
  `order_imported_at_raw` VARCHAR(32) NULL,
  `order_remark` TEXT NULL,
  `shipping_name` VARCHAR(128) NULL,
  `shipping_postal_code` VARCHAR(32) NULL,
  `shipping_prefecture` VARCHAR(64) NULL,
  `shipping_city` VARCHAR(128) NULL,
  `shipping_address` TEXT NULL,
  `shipping_phone` VARCHAR(64) NULL,
  `delivery_method` VARCHAR(128) NULL,
  `delivery_date_raw` VARCHAR(32) NULL,
  `delivery_time_slot` VARCHAR(64) NULL,
  `shipment_request_no` VARCHAR(128) NULL,
  `product_name_extra` TEXT NULL,
  `source_file_name` VARCHAR(255) NULL,
  `source_file_path` VARCHAR(512) NULL,
  `raw_payload` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  UNIQUE INDEX `order_records_row_hash_key`(`row_hash`),
  INDEX `order_records_order_id_idx`(`order_id`),
  INDEX `order_records_mall_order_no_idx`(`mall_order_no`),
  INDEX `order_records_sku_code_idx`(`sku_code`),
  INDEX `order_records_created_at_idx`(`created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
