CREATE TABLE `amazon_order_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `row_hash` CHAR(40) NOT NULL,
  `order_id` VARCHAR(64) NULL,
  `order_item_id` VARCHAR(64) NULL,
  `purchase_date_raw` VARCHAR(64) NULL,
  `payments_date_raw` VARCHAR(64) NULL,
  `reporting_date_raw` VARCHAR(64) NULL,
  `promise_date_raw` VARCHAR(64) NULL,
  `days_past_promise` INTEGER NULL,
  `buyer_email` VARCHAR(255) NULL,
  `buyer_name` VARCHAR(255) NULL,
  `buyer_phone_number` VARCHAR(64) NULL,
  `sku` VARCHAR(128) NULL,
  `product_name` TEXT NULL,
  `quantity_purchased` INTEGER NULL,
  `quantity_shipped` INTEGER NULL,
  `quantity_to_ship` INTEGER NULL,
  `ship_service_level` VARCHAR(128) NULL,
  `recipient_name` VARCHAR(255) NULL,
  `ship_address_1` TEXT NULL,
  `ship_address_2` TEXT NULL,
  `ship_address_3` TEXT NULL,
  `ship_city` VARCHAR(255) NULL,
  `ship_state` VARCHAR(255) NULL,
  `ship_postal_code` VARCHAR(32) NULL,
  `ship_country` VARCHAR(32) NULL,
  `customized_url` TEXT NULL,
  `customized_page` TEXT NULL,
  `is_business_order` BOOLEAN NULL,
  `purchase_order_number` VARCHAR(128) NULL,
  `price_designation` VARCHAR(128) NULL,
  `verge_of_cancellation` BOOLEAN NULL,
  `verge_of_late_shipment` BOOLEAN NULL,
  `mall_name` VARCHAR(128) NULL,
  `shop_name` VARCHAR(128) NULL,
  `shipment_company` VARCHAR(128) NULL,
  `shipment_no` VARCHAR(128) NULL,
  `shipment_no_registered_at` DATETIME(3) NULL,
  `source_file_name` VARCHAR(255) NULL,
  `source_file_path` VARCHAR(512) NULL,
  `raw_payload` JSON NULL,
  `csv_imported_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `amazon_order_records_row_hash_key`(`row_hash`),
  INDEX `amazon_order_records_order_id_idx`(`order_id`),
  INDEX `amazon_order_records_order_item_id_idx`(`order_item_id`),
  INDEX `amazon_order_records_sku_idx`(`sku`),
  INDEX `amazon_order_records_csv_imported_at_idx`(`csv_imported_at`),
  INDEX `amazon_order_records_created_at_idx`(`created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
