CREATE TABLE `return_records` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_name` VARCHAR(255) NULL,
  `carrier_name` VARCHAR(128) NULL,
  `tracking_no` VARCHAR(128) NULL,
  `postal_code` VARCHAR(32) NULL,
  `address` TEXT NULL,
  `phone` VARCHAR(64) NULL,
  `package_content` TEXT NULL,
  `sales_site` VARCHAR(128) NULL,
  `order_no` VARCHAR(128) NULL,
  `product_id` VARCHAR(128) NULL,
  `product_name` VARCHAR(255) NULL,
  `is_opened_used` BOOLEAN NOT NULL DEFAULT false,
  `can_restock` BOOLEAN NOT NULL DEFAULT false,
  `source_file_name` VARCHAR(255) NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `return_records_created_at_idx` (`created_at`),
  INDEX `return_records_tracking_no_idx` (`tracking_no`),
  INDEX `return_records_order_no_idx` (`order_no`),
  INDEX `return_records_product_id_idx` (`product_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
