export const AuditEventType = {
  BOX_CREATED: 'box_created',
  BOX_FIELD_UPDATED: 'box_field_updated',
  BOX_RENAMED: 'box_renamed',
  BOX_DISABLED: 'box_disabled',
  BOX_DELETED: 'box_deleted',
  BOX_STOCK_INCREASED: 'box_stock_increased',
  BOX_STOCK_OUTBOUND: 'box_stock_outbound',
  SKU_CREATED: 'sku_created',
  SKU_FIELD_UPDATED: 'sku_field_updated',
  SKU_DISABLED: 'sku_disabled',
  SKU_DELETED: 'sku_deleted',
  SHELF_CREATED: 'shelf_created',
  SHELF_FIELD_UPDATED: 'shelf_field_updated',
  SHELF_DISABLED: 'shelf_disabled',
  SHELF_DELETED: 'shelf_deleted',
  BRAND_CREATED: 'brand_created',
  BRAND_UPDATED: 'brand_updated',
  BRAND_DELETED: 'brand_deleted',
  SKU_TYPE_CREATED: 'sku_type_created',
  SKU_TYPE_UPDATED: 'sku_type_updated',
  SKU_TYPE_DELETED: 'sku_type_deleted',
  SHOP_CREATED: 'shop_created',
  SHOP_UPDATED: 'shop_updated',
  SHOP_DELETED: 'shop_deleted',
  USER_CREATED: 'user_created',
  USER_UPDATED: 'user_updated',
  USER_DISABLED: 'user_disabled',
  USER_DELETED: 'user_deleted',
  INBOUND_ORDER_CREATED: 'inbound_order_created',
  INBOUND_ORDER_CONFIRMED: 'inbound_order_confirmed',
  INBOUND_ORDER_VOIDED: 'inbound_order_voided',
  OUTBOUND_ORDER_CREATED: 'outbound_order_created',
  OUTBOUND_ORDER_CONFIRMED: 'outbound_order_confirmed',
  OUTBOUND_ORDER_VOIDED: 'outbound_order_voided',
  STOCKTAKE_TASK_CREATED: 'stocktake_task_created',
  STOCKTAKE_TASK_STARTED: 'stocktake_task_started',
  STOCKTAKE_TASK_FINISHED: 'stocktake_task_finished',
  STOCKTAKE_TASK_VOIDED: 'stocktake_task_voided',
  INVENTORY_ADJUST_CREATED: 'inventory_adjust_created',
  INVENTORY_ADJUST_CONFIRMED: 'inventory_adjust_confirmed',
  INVENTORY_ADJUST_VOIDED: 'inventory_adjust_voided',
} as const;

export type AuditEventTypeValue = (typeof AuditEventType)[keyof typeof AuditEventType];
